const keyboardButtons = {
  id192: { en: { regular: '`', shift: '~' }, ru: { regular: 'ё', shift: 'Ё' }, type: 'key' },
  id49: { en: { regular: '1', shift: '!' }, ru: { regular: '1', shift: '!' }, type: 'key' },
  id50: { en: { regular: '2', shift: '@' }, ru: { regular: '2', shift: '"' }, type: 'key' },
  id51: { en: { regular: '3', shift: '#' }, ru: { regular: '3', shift: '№' }, type: 'key' },
  id52: { en: { regular: '4', shift: '$' }, ru: { regular: '4', shift: ';' }, type: 'key' },
  id53: { en: { regular: '5', shift: '%' }, ru: { regular: '5', shift: '%' }, type: 'key' },
  id54: { en: { regular: '6', shift: '^' }, ru: { regular: '6', shift: ':' }, type: 'key' },
  id55: { en: { regular: '7', shift: '&' }, ru: { regular: '7', shift: '?' }, type: 'key' },
  id56: { en: { regular: '8', shift: '*' }, ru: { regular: '8', shift: '*' }, type: 'key' },
  id57: { en: { regular: '9', shift: '(' }, ru: { regular: '9', shift: '(' }, type: 'key' },
  id48: { en: { regular: '0', shift: ')' }, ru: { regular: '0', shift: ')' }, type: 'key' },
  id189: { en: { regular: '-', shift: '_' }, ru: { regular: '-', shift: '_' }, type: 'key' },
  id187: { en: { regular: '=', shift: '+' }, ru: { regular: '=', shift: '+' }, type: 'key' },
  id8: { type: 'backspace' },
  id9: { type: 'tab' },
  id81: { en: { regular: 'q', shift: 'Q' }, ru: { regular: 'й', shift: 'Й' }, type: 'key' },
  id87: { en: { regular: 'w', shift: 'W' }, ru: { regular: 'ц', shift: 'Ц' }, type: 'key' },
  id69: { en: { regular: 'e', shift: 'E' }, ru: { regular: 'у', shift: 'У' }, type: 'key' },
  id82: { en: { regular: 'r', shift: 'R' }, ru: { regular: 'к', shift: 'К' }, type: 'key' },
  id84: { en: { regular: 't', shift: 'T' }, ru: { regular: 'е', shift: 'Е' }, type: 'key' },
  id89: { en: { regular: 'y', shift: 'Y' }, ru: { regular: 'н', shift: 'Н' }, type: 'key' },
  id85: { en: { regular: 'u', shift: 'U' }, ru: { regular: 'г', shift: 'Г' }, type: 'key' },
  id73: { en: { regular: 'i', shift: 'I' }, ru: { regular: 'ш', shift: 'Ш' }, type: 'key' },
  id79: { en: { regular: 'o', shift: 'O' }, ru: { regular: 'щ', shift: 'Щ' }, type: 'key' },
  id80: { en: { regular: 'p', shift: 'P' }, ru: { regular: 'з', shift: 'З' }, type: 'key' },
  id219: { en: { regular: '[', shift: '{' }, ru: { regular: 'х', shift: 'Х' }, type: 'key' },
  id221: { en: { regular: ']', shift: '}' }, ru: { regular: 'ъ', shift: 'Ъ' }, type: 'key' },
  id220: { en: { regular: '\\', shift: '|' }, ru: { regular: '\\', shift: '/' }, type: 'key' },
  id46: { type: 'delete' },
  id20: { type: 'capsLock' },
  id65: { en: { regular: 'a', shift: 'A' }, ru: { regular: 'ф', shift: 'Ф' }, type: 'key' },
  id83: { en: { regular: 's', shift: 'S' }, ru: { regular: 'ы', shift: 'Ы' }, type: 'key' },
  id68: { en: { regular: 'd', shift: 'D' }, ru: { regular: 'в', shift: 'В' }, type: 'key' },
  id70: { en: { regular: 'f', shift: 'F' }, ru: { regular: 'а', shift: 'А' }, type: 'key' },
  id71: { en: { regular: 'g', shift: 'G' }, ru: { regular: 'п', shift: 'П' }, type: 'key' },
  id72: { en: { regular: 'h', shift: 'H' }, ru: { regular: 'р', shift: 'Р' }, type: 'key' },
  id74: { en: { regular: 'j', shift: 'J' }, ru: { regular: 'о', shift: 'О' }, type: 'key' },
  id75: { en: { regular: 'k', shift: 'K' }, ru: { regular: 'л', shift: 'Л' }, type: 'key' },
  id76: { en: { regular: 'l', shift: 'L' }, ru: { regular: 'д', shift: 'Д' }, type: 'key' },
  id186: { en: { regular: ';', shift: ':' }, ru: { regular: 'ж', shift: 'Ж' }, type: 'key' },
  id222: { en: { regular: '\'', shift: '"' }, ru: { regular: 'э', shift: 'Э' }, type: 'key' },
  id13: { type: 'enter' },
  id16_left: { type: 'shift' },
  id90: { en: { regular: 'z', shift: 'Z' }, ru: { regular: 'я', shift: 'Я' }, type: 'key' },
  id88: { en: { regular: 'x', shift: 'X' }, ru: { regular: 'ч', shift: 'Ч' }, type: 'key' },
  id67: { en: { regular: 'c', shift: 'C' }, ru: { regular: 'с', shift: 'С' }, type: 'key' },
  id86: { en: { regular: 'v', shift: 'V' }, ru: { regular: 'м', shift: 'М' }, type: 'key' },
  id66: { en: { regular: 'b', shift: 'B' }, ru: { regular: 'и', shift: 'И' }, type: 'key' },
  id78: { en: { regular: 'n', shift: 'N' }, ru: { regular: 'т', shift: 'Т' }, type: 'key' },
  id77: { en: { regular: 'm', shift: 'M' }, ru: { regular: 'Ь', shift: 'ь' }, type: 'key' },
  id188: { en: { regular: ',', shift: '<' }, ru: { regular: 'б', shift: 'Б' }, type: 'key' },
  id190: { en: { regular: '.', shift: '>' }, ru: { regular: 'ю', shift: 'Ю' }, type: 'key' },
  id191: { en: { regular: '/', shift: '?' }, ru: { regular: '.', shift: ',' }, type: 'key' },
  id38: { type: 'up' },
  id16_right: { type: 'shift' },
  id17_left: { type: 'ctrl' },
  id91: { type: 'win' },
  id18_left: { type: 'alt' },
  id32: { type: 'space' },
  id18_right: { type: 'alt' },
  id37: { type: 'left' },
  id40: { type: 'down' },
  id39: { type: 'right' },
  id17_right: { type: 'ctrl' },
};

export default keyboardButtons;
