const keyboardButtons = {
  Backquote: { en: { regular: '`', shift: '~' }, ru: { regular: 'ё', shift: 'Ё' }, type: 'key' },
  Digit1: { en: { regular: '1', shift: '!' }, ru: { regular: '1', shift: '!' }, type: 'key' },
  Digit2: { en: { regular: '2', shift: '@' }, ru: { regular: '2', shift: '"' }, type: 'key' },
  Digit3: { en: { regular: '3', shift: '#' }, ru: { regular: '3', shift: '№' }, type: 'key' },
  Digit4: { en: { regular: '4', shift: '$' }, ru: { regular: '4', shift: ';' }, type: 'key' },
  Digit5: { en: { regular: '5', shift: '%' }, ru: { regular: '5', shift: '%' }, type: 'key' },
  Digit6: { en: { regular: '6', shift: '^' }, ru: { regular: '6', shift: ':' }, type: 'key' },
  Digit7: { en: { regular: '7', shift: '&' }, ru: { regular: '7', shift: '?' }, type: 'key' },
  Digit8: { en: { regular: '8', shift: '*' }, ru: { regular: '8', shift: '*' }, type: 'key' },
  Digit9: { en: { regular: '9', shift: '(' }, ru: { regular: '9', shift: '(' }, type: 'key' },
  Digit0: { en: { regular: '0', shift: ')' }, ru: { regular: '0', shift: ')' }, type: 'key' },
  Minus: { en: { regular: '-', shift: '_' }, ru: { regular: '-', shift: '_' }, type: 'key' },
  Equal: { en: { regular: '=', shift: '+' }, ru: { regular: '=', shift: '+' }, type: 'key' },
  Backspace: { type: 'backspace' },
  Tab: { type: 'tab' },
  KeyQ: { en: { regular: 'q', shift: 'Q' }, ru: { regular: 'й', shift: 'Й' }, type: 'key' },
  KeyW: { en: { regular: 'w', shift: 'W' }, ru: { regular: 'ц', shift: 'Ц' }, type: 'key' },
  KeyE: { en: { regular: 'e', shift: 'E' }, ru: { regular: 'у', shift: 'У' }, type: 'key' },
  KeyR: { en: { regular: 'r', shift: 'R' }, ru: { regular: 'к', shift: 'К' }, type: 'key' },
  KeyT: { en: { regular: 't', shift: 'T' }, ru: { regular: 'е', shift: 'Е' }, type: 'key' },
  KeyY: { en: { regular: 'y', shift: 'Y' }, ru: { regular: 'н', shift: 'Н' }, type: 'key' },
  KeyU: { en: { regular: 'u', shift: 'U' }, ru: { regular: 'г', shift: 'Г' }, type: 'key' },
  KeyI: { en: { regular: 'i', shift: 'I' }, ru: { regular: 'ш', shift: 'Ш' }, type: 'key' },
  KeyO: { en: { regular: 'o', shift: 'O' }, ru: { regular: 'щ', shift: 'Щ' }, type: 'key' },
  KeyP: { en: { regular: 'p', shift: 'P' }, ru: { regular: 'з', shift: 'З' }, type: 'key' },
  BracketLeft: { en: { regular: '[', shift: '{' }, ru: { regular: 'х', shift: 'Х' }, type: 'key' },
  BracketRight: { en: { regular: ']', shift: '}' }, ru: { regular: 'ъ', shift: 'Ъ' }, type: 'key' },
  Backslash: { en: { regular: '\\', shift: '|' }, ru: { regular: '\\', shift: '/' }, type: 'key' },
  Delete: { type: 'delete' },
  CapsLock: { type: 'capsLock' },
  KeyA: { en: { regular: 'a', shift: 'A' }, ru: { regular: 'ф', shift: 'Ф' }, type: 'key' },
  KeyS: { en: { regular: 's', shift: 'S' }, ru: { regular: 'ы', shift: 'Ы' }, type: 'key' },
  KeyD: { en: { regular: 'd', shift: 'D' }, ru: { regular: 'в', shift: 'В' }, type: 'key' },
  KeyF: { en: { regular: 'f', shift: 'F' }, ru: { regular: 'а', shift: 'А' }, type: 'key' },
  KeyG: { en: { regular: 'g', shift: 'G' }, ru: { regular: 'п', shift: 'П' }, type: 'key' },
  KeyH: { en: { regular: 'h', shift: 'H' }, ru: { regular: 'р', shift: 'Р' }, type: 'key' },
  KeyJ: { en: { regular: 'j', shift: 'J' }, ru: { regular: 'о', shift: 'О' }, type: 'key' },
  KeyK: { en: { regular: 'k', shift: 'K' }, ru: { regular: 'л', shift: 'Л' }, type: 'key' },
  KeyL: { en: { regular: 'l', shift: 'L' }, ru: { regular: 'д', shift: 'Д' }, type: 'key' },
  Semicolon: { en: { regular: ';', shift: ':' }, ru: { regular: 'ж', shift: 'Ж' }, type: 'key' },
  Quote: { en: { regular: '\'', shift: '"' }, ru: { regular: 'э', shift: 'Э' }, type: 'key' },
  Enter: { type: 'enter' },
  ShiftLeft: { type: 'shift' },
  KeyZ: { en: { regular: 'z', shift: 'Z' }, ru: { regular: 'я', shift: 'Я' }, type: 'key' },
  KeyX: { en: { regular: 'x', shift: 'X' }, ru: { regular: 'ч', shift: 'Ч' }, type: 'key' },
  KeyC: { en: { regular: 'c', shift: 'C' }, ru: { regular: 'с', shift: 'С' }, type: 'key' },
  KeyV: { en: { regular: 'v', shift: 'V' }, ru: { regular: 'м', shift: 'М' }, type: 'key' },
  KeyB: { en: { regular: 'b', shift: 'B' }, ru: { regular: 'и', shift: 'И' }, type: 'key' },
  KeyN: { en: { regular: 'n', shift: 'N' }, ru: { regular: 'т', shift: 'Т' }, type: 'key' },
  KeyM: { en: { regular: 'm', shift: 'M' }, ru: { regular: 'Ь', shift: 'ь' }, type: 'key' },
  Comma: { en: { regular: ',', shift: '<' }, ru: { regular: 'б', shift: 'Б' }, type: 'key' },
  Period: { en: { regular: '.', shift: '>' }, ru: { regular: 'ю', shift: 'Ю' }, type: 'key' },
  Slash: { en: { regular: '/', shift: '?' }, ru: { regular: '.', shift: ',' }, type: 'key' },
  ArrowUp: { type: 'up' },
  ShiftRight: { type: 'shift' },
  ControlLeft: { type: 'ctrl' },
  MetaLeft: { type: 'win' },
  AltLeft: { type: 'alt' },
  Space: { type: 'space' },
  AltRight: { type: 'alt' },
  ArrowLeft: { type: 'left' },
  ArrowDown: { type: 'down' },
  ArrowRight: { type: 'right' },
  ControlRight: { type: 'ctrl' },
};

const letters = [
  'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY',
  'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft',
  'BracketRight', 'Backslash', 'KeyA', 'KeyS',
  'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK',
  'KeyL', 'Semicolon', 'Quote', 'KeyZ', 'KeyX',
  'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma',
  'Period', 'Slash', 'Tab'];

export { keyboardButtons, letters };
